# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 430375ebf316c76ddf3ddbe1d2c4b7da8d72bb6509e44122c823f78fb0b4fffbd3f738c21b9c7d61ab49be8aa938e4e360deeb9f1c6100f028f5124c66c44649

test:
  secret_key_base: bff78a024b991387ba43fe5ffa9b0114d84f5d4fa3d66feb1aa6809438ad1a6a7d970a147508021cf977e312b1200f4387a4ceea696ee6e6a7c2b2dbc3db30d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
